name: floca
description: Library for Flutter app localization. Generates Dart code with string constants, ready to plug into MaterialApp.
repository: https://github.com/rtmigo/floca_flutter
version: 0.1.7+0


environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  csv: ^5.0.0
  flutter_lints: ^2.0.1

dev_dependencies:
  test: any
