name: floca
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  csv: ^5.0.0
  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: any
